services:
  - docker
language: java
dist: bionic
jdk:
  - openjdk14
cache:
  directories:
    - "$HOME/.m2"
env:
  global:
    - DOCKER_IMAGE=venoexe/chat-admin:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
    - secure: ay5JpiIJD9yyK57P32EOufdKx+6zbmo2UN+y0mw3RFmbeGlI/QLUSyVHnbAsorgN3pw4aThWO08iIsCV5ICVbiX5WM8s3C7bDsfZHjMJCvPSOGnUDZZu2pUYPEf7OLsrJoIYSyJEj8po4vrKr+NpDKB1q2O2NxLrqXDl4i3MUTBzTnvrVZ27k1a0FS/b/VVmVyKieeGjPVQqvV3w6RUvvAwre/rWgGrfiMzBxOEcW0uQnPgQ4sVT2Wc1BQwNuVWXWEUDjgjDEfEZVxP9CK7/769ewyVXzhzIG10tpIXA3TpfbUgcknE+v0Ms9sDly0hWJB5k8MJApgiqIKbZ38fK8icAXHOkaiiHxZus9S3B4VSGVVV5d0XUsE+Xug5mQLG57n2GRss/c2ngfR11Z+DAWcupZ+1Ors5lheUhMjDeJWPkJSrJ1NPASUJb4OZP7omj4RaVeK5Owf1m616LADnplsVvHH3LfCWa3LWRgYhRn7fkp7sFAdUrQpcEaO7zz9pG3KJuGvl0pOT5QteO2toqgRyjTjOF+KnuqcBfuG4pawPawm8o3cZwpds3aXoV9W7L60+zsBLUGvLxds1phyvUTdhbTN82RfOVRGGq7N2xBVdzZwb+RJb+bxQNyuX/YVTtb9Trut/YJpHA2GveOB61pEmkRIWPuF/vh+rPwqkbCaM=
    - secure: WZ09q2h4N2Q0wFyBkqyhZvjpT0K4f/omSIU4sLY0SVPPPUsZRxrbyGu26bmY6s8w2c+dx7gWDKB4XvVs9uLGk8v4knCzAkVt4YbpaD4WwPxJJ43rSvfg/vuchWKp/xHrW1fy3qEuljIuImQPth8bTmYvTlly7JWSOchkKtIsohH8l9zE5xG+AJ6jg5iewDasY638BJPC+33Jy8Dr8oQDZ/TuYthX0N9FSA6DTa9hL2Om9dE28mgfEpZCvzThLatw+51rggPXnPHd9B/WUEbra7ejoTuzVeJd0687M+Fn5Yn/C3iXR8avc2TmwLiXFnyqr1PxJat0rLLY7zMLfAiD8x2C6mRBd8nAVKefjjNunf487+YdTmqNMqWiI+rYBJcBF2BYJPuM4ISkftGhTS+f1uuUCfSxqZt8k97uzb0nDYi4AtVNntv6/s8VE0xAM6JVpmAO/C7LSfUlHMpr9dkJAi8ZzoltX+bzGJNQrPsZr0CCoEWz3hQtJ5fYhCoptV2e0YtWH19pKNByJQiZKUTb5G4RYUJ58Tk2BvBf2KJcKpeEWxbDuQk0nRdKBo3N3lD9zaLYtql0/LJfEspSCt8IWMkAPaZ2RI6CGLTQEhHqb9fCExsTrpt+S/2flnhdSXeAC3jOSnO3cPtIPFqCaiTq7bsqK6dcOu1ObkXbQKAErL4=
script:
  - mvn clean package -U
  - docker build -t "$DOCKER_IMAGE" .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"
