apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-admin
  template:
    metadata:
      labels:
        app: chat-admin
    spec:
      containers:
        - image: venoexe/chat-admin:1.0.0-SNAPSHOT-15.1
          name: chat-admin
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: postgres://kandula.db.elephantsql.com:5432/kbrnjtfi
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: kbrnjtfi
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: chat-admin
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: chat-admin
